// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnyValue {
    #[prost(oneof = "any_value::Value", tags = "1, 2, 3, 4, 5, 6, 7")]
    pub value: ::core::option::Option<any_value::Value>,
}
/// Nested message and enum types in `AnyValue`.
pub mod any_value {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "1")]
        StringValue(::prost::alloc::string::String),
        #[prost(bool, tag = "2")]
        BoolValue(bool),
        #[prost(int64, tag = "3")]
        IntValue(i64),
        #[prost(double, tag = "4")]
        DoubleValue(f64),
        #[prost(message, tag = "5")]
        ArrayValue(super::ArrayValue),
        #[prost(message, tag = "6")]
        KvlistValue(super::KeyValueList),
        #[prost(bytes, tag = "7")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ArrayValue {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<AnyValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValueList {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<KeyValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KeyValue {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<AnyValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentToServer {
    #[prost(bytes = "vec", tag = "1")]
    pub instance_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub sequence_num: u64,
    #[prost(message, optional, tag = "3")]
    pub agent_description: ::core::option::Option<AgentDescription>,
    #[prost(uint64, tag = "4")]
    pub capabilities: u64,
    #[prost(message, optional, tag = "5")]
    pub health: ::core::option::Option<ComponentHealth>,
    #[prost(message, optional, tag = "6")]
    pub effective_config: ::core::option::Option<EffectiveConfig>,
    #[prost(message, optional, tag = "7")]
    pub remote_config_status: ::core::option::Option<RemoteConfigStatus>,
    #[prost(message, optional, tag = "8")]
    pub package_statuses: ::core::option::Option<PackageStatuses>,
    #[prost(message, optional, tag = "9")]
    pub agent_disconnect: ::core::option::Option<AgentDisconnect>,
    #[prost(uint64, tag = "10")]
    pub flags: u64,
    #[prost(message, optional, tag = "11")]
    pub connection_settings_request: ::core::option::Option<ConnectionSettingsRequest>,
    #[prost(message, optional, tag = "12")]
    pub custom_capabilities: ::core::option::Option<CustomCapabilities>,
    #[prost(message, optional, tag = "13")]
    pub custom_message: ::core::option::Option<CustomMessage>,
    #[prost(message, optional, tag = "14")]
    pub available_components: ::core::option::Option<AvailableComponents>,
    #[prost(message, optional, tag = "15")]
    pub connection_settings_status: ::core::option::Option<ConnectionSettingsStatus>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentDisconnect {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConnectionSettingsRequest {
    #[prost(message, optional, tag = "1")]
    pub opamp: ::core::option::Option<OpAmpConnectionSettingsRequest>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpAmpConnectionSettingsRequest {
    #[prost(message, optional, tag = "1")]
    pub certificate_request: ::core::option::Option<CertificateRequest>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CertificateRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub csr: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AvailableComponents {
    #[prost(map = "string, message", tag = "1")]
    pub components: ::std::collections::HashMap<::prost::alloc::string::String, ComponentDetails>,
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComponentDetails {
    #[prost(message, repeated, tag = "1")]
    pub metadata: ::prost::alloc::vec::Vec<KeyValue>,
    #[prost(map = "string, message", tag = "2")]
    pub sub_component_map: ::std::collections::HashMap<::prost::alloc::string::String, ComponentDetails>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ServerToAgent {
    #[prost(bytes = "vec", tag = "1")]
    pub instance_uid: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub error_response: ::core::option::Option<ServerErrorResponse>,
    #[prost(message, optional, tag = "3")]
    pub remote_config: ::core::option::Option<AgentRemoteConfig>,
    #[prost(message, optional, tag = "4")]
    pub connection_settings: ::core::option::Option<ConnectionSettingsOffers>,
    #[prost(message, optional, tag = "5")]
    pub packages_available: ::core::option::Option<PackagesAvailable>,
    #[prost(uint64, tag = "6")]
    pub flags: u64,
    #[prost(uint64, tag = "7")]
    pub capabilities: u64,
    #[prost(message, optional, tag = "8")]
    pub agent_identification: ::core::option::Option<AgentIdentification>,
    #[prost(message, optional, tag = "9")]
    pub command: ::core::option::Option<ServerToAgentCommand>,
    #[prost(message, optional, tag = "10")]
    pub custom_capabilities: ::core::option::Option<CustomCapabilities>,
    #[prost(message, optional, tag = "11")]
    pub custom_message: ::core::option::Option<CustomMessage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OpAmpConnectionSettings {
    #[prost(string, tag = "1")]
    pub destination_endpoint: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub headers: ::core::option::Option<Headers>,
    #[prost(message, optional, tag = "3")]
    pub certificate: ::core::option::Option<TlsCertificate>,
    #[prost(uint64, tag = "4")]
    pub heartbeat_interval_seconds: u64,
    #[prost(message, optional, tag = "5")]
    pub tls: ::core::option::Option<TlsConnectionSettings>,
    #[prost(message, optional, tag = "6")]
    pub proxy: ::core::option::Option<ProxyConnectionSettings>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TelemetryConnectionSettings {
    #[prost(string, tag = "1")]
    pub destination_endpoint: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub headers: ::core::option::Option<Headers>,
    #[prost(message, optional, tag = "3")]
    pub certificate: ::core::option::Option<TlsCertificate>,
    #[prost(message, optional, tag = "4")]
    pub tls: ::core::option::Option<TlsConnectionSettings>,
    #[prost(message, optional, tag = "5")]
    pub proxy: ::core::option::Option<ProxyConnectionSettings>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OtherConnectionSettings {
    #[prost(string, tag = "1")]
    pub destination_endpoint: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub headers: ::core::option::Option<Headers>,
    #[prost(message, optional, tag = "3")]
    pub certificate: ::core::option::Option<TlsCertificate>,
    #[prost(map = "string, string", tag = "4")]
    pub other_settings: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub tls: ::core::option::Option<TlsConnectionSettings>,
    #[prost(message, optional, tag = "6")]
    pub proxy: ::core::option::Option<ProxyConnectionSettings>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TlsConnectionSettings {
    #[prost(string, tag = "1")]
    pub ca_pem_contents: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub include_system_ca_certs_pool: bool,
    #[prost(bool, tag = "3")]
    pub insecure_skip_verify: bool,
    #[prost(string, tag = "4")]
    pub min_version: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub max_version: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "6")]
    pub cipher_suites: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProxyConnectionSettings {
    #[prost(string, tag = "1")]
    pub url: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub connect_headers: ::core::option::Option<Headers>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Headers {
    #[prost(message, repeated, tag = "1")]
    pub headers: ::prost::alloc::vec::Vec<Header>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Header {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TlsCertificate {
    #[prost(bytes = "vec", tag = "1")]
    pub cert: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub private_key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub ca_cert: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConnectionSettingsOffers {
    #[prost(bytes = "vec", tag = "1")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "2")]
    pub opamp: ::core::option::Option<OpAmpConnectionSettings>,
    #[prost(message, optional, tag = "3")]
    pub own_metrics: ::core::option::Option<TelemetryConnectionSettings>,
    #[prost(message, optional, tag = "4")]
    pub own_traces: ::core::option::Option<TelemetryConnectionSettings>,
    #[prost(message, optional, tag = "5")]
    pub own_logs: ::core::option::Option<TelemetryConnectionSettings>,
    #[prost(map = "string, message", tag = "6")]
    pub other_connections: ::std::collections::HashMap<::prost::alloc::string::String, OtherConnectionSettings>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackagesAvailable {
    #[prost(map = "string, message", tag = "1")]
    pub packages: ::std::collections::HashMap<::prost::alloc::string::String, PackageAvailable>,
    #[prost(bytes = "vec", tag = "2")]
    pub all_packages_hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageAvailable {
    #[prost(enumeration = "PackageType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub file: ::core::option::Option<DownloadableFile>,
    #[prost(bytes = "vec", tag = "4")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DownloadableFile {
    #[prost(string, tag = "1")]
    pub download_url: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub content_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub signature: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "4")]
    pub headers: ::core::option::Option<Headers>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerErrorResponse {
    #[prost(enumeration = "ServerErrorResponseType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(oneof = "server_error_response::Details", tags = "3")]
    pub details: ::core::option::Option<server_error_response::Details>,
}
/// Nested message and enum types in `ServerErrorResponse`.
pub mod server_error_response {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Details {
        #[prost(message, tag = "3")]
        RetryInfo(super::RetryInfo),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetryInfo {
    #[prost(uint64, tag = "1")]
    pub retry_after_nanoseconds: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerToAgentCommand {
    #[prost(enumeration = "CommandType", tag = "1")]
    pub r#type: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentDescription {
    #[prost(message, repeated, tag = "1")]
    pub identifying_attributes: ::prost::alloc::vec::Vec<KeyValue>,
    #[prost(message, repeated, tag = "2")]
    pub non_identifying_attributes: ::prost::alloc::vec::Vec<KeyValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComponentHealth {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(fixed64, tag = "2")]
    pub start_time_unix_nano: u64,
    #[prost(string, tag = "3")]
    pub last_error: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub status: ::prost::alloc::string::String,
    #[prost(fixed64, tag = "5")]
    pub status_time_unix_nano: u64,
    #[prost(map = "string, message", tag = "6")]
    pub component_health_map: ::std::collections::HashMap<::prost::alloc::string::String, ComponentHealth>,
    #[prost(message, repeated, tag = "7")]
    pub attributes: ::prost::alloc::vec::Vec<KeyValue>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EffectiveConfig {
    #[prost(message, optional, tag = "1")]
    pub config_map: ::core::option::Option<AgentConfigMap>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoteConfigStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub last_remote_config_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "RemoteConfigStatuses", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ConnectionSettingsStatus {
    #[prost(bytes = "vec", tag = "1")]
    pub last_connection_settings_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "ConnectionSettingsStatuses", tag = "2")]
    pub status: i32,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageStatuses {
    #[prost(map = "string, message", tag = "1")]
    pub packages: ::std::collections::HashMap<::prost::alloc::string::String, PackageStatus>,
    #[prost(bytes = "vec", tag = "2")]
    pub server_provided_all_packages_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub error_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PackageStatus {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub agent_has_version: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub agent_has_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "4")]
    pub server_offered_version: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "5")]
    pub server_offered_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(enumeration = "PackageStatusEnum", tag = "6")]
    pub status: i32,
    #[prost(string, tag = "7")]
    pub error_message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "8")]
    pub download_details: ::core::option::Option<PackageDownloadDetails>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PackageDownloadDetails {
    #[prost(double, tag = "1")]
    pub download_percent: f64,
    #[prost(double, tag = "2")]
    pub download_bytes_per_second: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentIdentification {
    #[prost(bytes = "vec", tag = "1")]
    pub new_instance_uid: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentRemoteConfig {
    #[prost(message, optional, tag = "1")]
    pub config: ::core::option::Option<AgentConfigMap>,
    #[prost(bytes = "vec", tag = "2")]
    pub config_hash: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentConfigMap {
    #[prost(map = "string, message", tag = "1")]
    pub config_map: ::std::collections::HashMap<::prost::alloc::string::String, AgentConfigFile>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AgentConfigFile {
    #[prost(bytes = "vec", tag = "1")]
    pub body: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "2")]
    pub content_type: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CustomCapabilities {
    #[prost(string, repeated, tag = "1")]
    pub capabilities: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CustomMessage {
    #[prost(string, tag = "1")]
    pub capability: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AgentToServerFlags {
    Unspecified = 0,
    RequestInstanceUid = 1,
}
impl AgentToServerFlags {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AgentToServerFlags_Unspecified",
            Self::RequestInstanceUid => "AgentToServerFlags_RequestInstanceUid",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AgentToServerFlags_Unspecified" => Some(Self::Unspecified),
            "AgentToServerFlags_RequestInstanceUid" => Some(Self::RequestInstanceUid),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ServerToAgentFlags {
    Unspecified = 0,
    ReportFullState = 1,
    ReportAvailableComponents = 2,
}
impl ServerToAgentFlags {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ServerToAgentFlags_Unspecified",
            Self::ReportFullState => "ServerToAgentFlags_ReportFullState",
            Self::ReportAvailableComponents => "ServerToAgentFlags_ReportAvailableComponents",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ServerToAgentFlags_Unspecified" => Some(Self::Unspecified),
            "ServerToAgentFlags_ReportFullState" => Some(Self::ReportFullState),
            "ServerToAgentFlags_ReportAvailableComponents" => Some(Self::ReportAvailableComponents),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ServerCapabilities {
    Unspecified = 0,
    AcceptsStatus = 1,
    OffersRemoteConfig = 2,
    AcceptsEffectiveConfig = 4,
    OffersPackages = 8,
    AcceptsPackagesStatus = 16,
    OffersConnectionSettings = 32,
    AcceptsConnectionSettingsRequest = 64,
}
impl ServerCapabilities {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ServerCapabilities_Unspecified",
            Self::AcceptsStatus => "ServerCapabilities_AcceptsStatus",
            Self::OffersRemoteConfig => "ServerCapabilities_OffersRemoteConfig",
            Self::AcceptsEffectiveConfig => "ServerCapabilities_AcceptsEffectiveConfig",
            Self::OffersPackages => "ServerCapabilities_OffersPackages",
            Self::AcceptsPackagesStatus => "ServerCapabilities_AcceptsPackagesStatus",
            Self::OffersConnectionSettings => "ServerCapabilities_OffersConnectionSettings",
            Self::AcceptsConnectionSettingsRequest => "ServerCapabilities_AcceptsConnectionSettingsRequest",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ServerCapabilities_Unspecified" => Some(Self::Unspecified),
            "ServerCapabilities_AcceptsStatus" => Some(Self::AcceptsStatus),
            "ServerCapabilities_OffersRemoteConfig" => Some(Self::OffersRemoteConfig),
            "ServerCapabilities_AcceptsEffectiveConfig" => Some(Self::AcceptsEffectiveConfig),
            "ServerCapabilities_OffersPackages" => Some(Self::OffersPackages),
            "ServerCapabilities_AcceptsPackagesStatus" => Some(Self::AcceptsPackagesStatus),
            "ServerCapabilities_OffersConnectionSettings" => Some(Self::OffersConnectionSettings),
            "ServerCapabilities_AcceptsConnectionSettingsRequest" => Some(Self::AcceptsConnectionSettingsRequest),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PackageType {
    TopLevel = 0,
    Addon = 1,
}
impl PackageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::TopLevel => "PackageType_TopLevel",
            Self::Addon => "PackageType_Addon",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PackageType_TopLevel" => Some(Self::TopLevel),
            "PackageType_Addon" => Some(Self::Addon),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ServerErrorResponseType {
    Unknown = 0,
    BadRequest = 1,
    Unavailable = 2,
}
impl ServerErrorResponseType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "ServerErrorResponseType_Unknown",
            Self::BadRequest => "ServerErrorResponseType_BadRequest",
            Self::Unavailable => "ServerErrorResponseType_Unavailable",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ServerErrorResponseType_Unknown" => Some(Self::Unknown),
            "ServerErrorResponseType_BadRequest" => Some(Self::BadRequest),
            "ServerErrorResponseType_Unavailable" => Some(Self::Unavailable),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CommandType {
    Restart = 0,
}
impl CommandType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Restart => "CommandType_Restart",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CommandType_Restart" => Some(Self::Restart),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AgentCapabilities {
    Unspecified = 0,
    ReportsStatus = 1,
    AcceptsRemoteConfig = 2,
    ReportsEffectiveConfig = 4,
    AcceptsPackages = 8,
    ReportsPackageStatuses = 16,
    ReportsOwnTraces = 32,
    ReportsOwnMetrics = 64,
    ReportsOwnLogs = 128,
    AcceptsOpAmpConnectionSettings = 256,
    AcceptsOtherConnectionSettings = 512,
    AcceptsRestartCommand = 1024,
    ReportsHealth = 2048,
    ReportsRemoteConfig = 4096,
    ReportsHeartbeat = 8192,
    ReportsAvailableComponents = 16384,
    ReportsConnectionSettingsStatus = 32768,
}
impl AgentCapabilities {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AgentCapabilities_Unspecified",
            Self::ReportsStatus => "AgentCapabilities_ReportsStatus",
            Self::AcceptsRemoteConfig => "AgentCapabilities_AcceptsRemoteConfig",
            Self::ReportsEffectiveConfig => "AgentCapabilities_ReportsEffectiveConfig",
            Self::AcceptsPackages => "AgentCapabilities_AcceptsPackages",
            Self::ReportsPackageStatuses => "AgentCapabilities_ReportsPackageStatuses",
            Self::ReportsOwnTraces => "AgentCapabilities_ReportsOwnTraces",
            Self::ReportsOwnMetrics => "AgentCapabilities_ReportsOwnMetrics",
            Self::ReportsOwnLogs => "AgentCapabilities_ReportsOwnLogs",
            Self::AcceptsOpAmpConnectionSettings => "AgentCapabilities_AcceptsOpAMPConnectionSettings",
            Self::AcceptsOtherConnectionSettings => "AgentCapabilities_AcceptsOtherConnectionSettings",
            Self::AcceptsRestartCommand => "AgentCapabilities_AcceptsRestartCommand",
            Self::ReportsHealth => "AgentCapabilities_ReportsHealth",
            Self::ReportsRemoteConfig => "AgentCapabilities_ReportsRemoteConfig",
            Self::ReportsHeartbeat => "AgentCapabilities_ReportsHeartbeat",
            Self::ReportsAvailableComponents => "AgentCapabilities_ReportsAvailableComponents",
            Self::ReportsConnectionSettingsStatus => "AgentCapabilities_ReportsConnectionSettingsStatus",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AgentCapabilities_Unspecified" => Some(Self::Unspecified),
            "AgentCapabilities_ReportsStatus" => Some(Self::ReportsStatus),
            "AgentCapabilities_AcceptsRemoteConfig" => Some(Self::AcceptsRemoteConfig),
            "AgentCapabilities_ReportsEffectiveConfig" => Some(Self::ReportsEffectiveConfig),
            "AgentCapabilities_AcceptsPackages" => Some(Self::AcceptsPackages),
            "AgentCapabilities_ReportsPackageStatuses" => Some(Self::ReportsPackageStatuses),
            "AgentCapabilities_ReportsOwnTraces" => Some(Self::ReportsOwnTraces),
            "AgentCapabilities_ReportsOwnMetrics" => Some(Self::ReportsOwnMetrics),
            "AgentCapabilities_ReportsOwnLogs" => Some(Self::ReportsOwnLogs),
            "AgentCapabilities_AcceptsOpAMPConnectionSettings" => Some(Self::AcceptsOpAmpConnectionSettings),
            "AgentCapabilities_AcceptsOtherConnectionSettings" => Some(Self::AcceptsOtherConnectionSettings),
            "AgentCapabilities_AcceptsRestartCommand" => Some(Self::AcceptsRestartCommand),
            "AgentCapabilities_ReportsHealth" => Some(Self::ReportsHealth),
            "AgentCapabilities_ReportsRemoteConfig" => Some(Self::ReportsRemoteConfig),
            "AgentCapabilities_ReportsHeartbeat" => Some(Self::ReportsHeartbeat),
            "AgentCapabilities_ReportsAvailableComponents" => Some(Self::ReportsAvailableComponents),
            "AgentCapabilities_ReportsConnectionSettingsStatus" => Some(Self::ReportsConnectionSettingsStatus),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ConnectionSettingsStatuses {
    Unset = 0,
    Applied = 1,
    Applying = 2,
    Failed = 3,
}
impl ConnectionSettingsStatuses {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unset => "ConnectionSettingsStatuses_UNSET",
            Self::Applied => "ConnectionSettingsStatuses_APPLIED",
            Self::Applying => "ConnectionSettingsStatuses_APPLYING",
            Self::Failed => "ConnectionSettingsStatuses_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ConnectionSettingsStatuses_UNSET" => Some(Self::Unset),
            "ConnectionSettingsStatuses_APPLIED" => Some(Self::Applied),
            "ConnectionSettingsStatuses_APPLYING" => Some(Self::Applying),
            "ConnectionSettingsStatuses_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RemoteConfigStatuses {
    Unset = 0,
    Applied = 1,
    Applying = 2,
    Failed = 3,
}
impl RemoteConfigStatuses {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unset => "RemoteConfigStatuses_UNSET",
            Self::Applied => "RemoteConfigStatuses_APPLIED",
            Self::Applying => "RemoteConfigStatuses_APPLYING",
            Self::Failed => "RemoteConfigStatuses_FAILED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RemoteConfigStatuses_UNSET" => Some(Self::Unset),
            "RemoteConfigStatuses_APPLIED" => Some(Self::Applied),
            "RemoteConfigStatuses_APPLYING" => Some(Self::Applying),
            "RemoteConfigStatuses_FAILED" => Some(Self::Failed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PackageStatusEnum {
    Installed = 0,
    InstallPending = 1,
    Installing = 2,
    InstallFailed = 3,
    Downloading = 4,
}
impl PackageStatusEnum {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Installed => "PackageStatusEnum_Installed",
            Self::InstallPending => "PackageStatusEnum_InstallPending",
            Self::Installing => "PackageStatusEnum_Installing",
            Self::InstallFailed => "PackageStatusEnum_InstallFailed",
            Self::Downloading => "PackageStatusEnum_Downloading",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PackageStatusEnum_Installed" => Some(Self::Installed),
            "PackageStatusEnum_InstallPending" => Some(Self::InstallPending),
            "PackageStatusEnum_Installing" => Some(Self::Installing),
            "PackageStatusEnum_InstallFailed" => Some(Self::InstallFailed),
            "PackageStatusEnum_Downloading" => Some(Self::Downloading),
            _ => None,
        }
    }
}
