version: otel_dataflow/v1
engine: {}
groups:
  default:
    pipelines:
      main:
        nodes:
          receiver:
            type: receiver:traffic_generator
            config:
              data_source: static
              generation_strategy: fresh
              traffic_config:
                max_signal_count: 8
                max_batch_size: 1
                log_weight: 1
                metric_weight: 0
                trace_weight: 0

              resource_attributes:
                - attrs:
                    tenant.id: prod
                  weight: 3
                - attrs:
                    tenant.id: ppe
                  weight: 1

          debug:
            type: processor:debug
            config:
              verbosity: detailed

          noop:
            type: exporter:noop

        connections:
          - from: receiver
            to: debug
          - from: debug
            to: noop
