rust:
- changed-files:
  - any-glob-to-any-file: 'rust/**/*'
go:
- changed-files:
  - any-glob-to-any-file: 'go/**/*'

ci/cd:
- changed-files:
  - any-glob-to-any-file: '.github/**/*'
- changed-files: