[package]
name = "otel-arrow-dfe-query-engine-languages"
description = "Query engine language parsers for OTAP dataflow"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
publish = true
keywords = ["opentelemetry", "otlp", "otap", "query", "parser"]
categories = ["parser-implementations"]
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
chrono = { workspace = true }
iso8601 = { workspace = true }
otel-arrow-contrib-data-engine-parser-abstractions = { workspace = true }
otel-arrow-contrib-data-engine-expressions = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
chrono-tz = { workspace = true }
pretty_assertions = { workspace = true }
