[package]
name = "otel-arrow-dfe-telemetry"
description = "Type-safe and NUMA-aware internal telemetry system (ITS)"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
publish = true
keywords = ["telemetry", "opentelemetry", "otlp", "otap", "observability"]
categories = ["development-tools"]
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
testing = []
unsafe-optimizations = ["unchecked-index", "unchecked-arithmetic"]
unchecked-index = []
unchecked-arithmetic = []

[dependencies]
otel-arrow-dfe-pdata = { workspace = true }
otel-arrow-dfe-config = { workspace = true }
otel-arrow-dfe-pdata-views = { workspace = true }
otel-arrow-dfe-telemetry-macros = { workspace = true }
otel-arrow-dfe-expohisto = { workspace = true }

bytes = { workspace = true }
chrono = { workspace = true }
flume = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
slotmap = { workspace = true }
parking_lot = { workspace = true }
serde = { workspace = true }
smallvec = { workspace = true }
arc-swap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter","registry", "std", "fmt"] }

opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true }
opentelemetry-resource-detectors = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
temp-env = { workspace = true }
tempfile = { workspace = true }
otel-arrow-dfe-pdata = { workspace = true, features = ["testing"] }
prost = { workspace = true }

[[bench]]
name = "distribution_record"
harness = false
