receivers:
  otelarrow:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
    admission:
      # memory limits applies to OTAP and OTLP data.
      request_limit_mib: 256
      waiting_limit_mib: 32

exporters:
  otelarrow:
    endpoint: '{{backend_hostname}}:1235'
    compression: none
    arrow:
      payload_compression: zstd
      # 5 matches DFE OTAP exporter default
      num_streams: 5

    # 100 standing requests (on 5 streams), asynchronous, no batching.
    sending_queue:
      enabled: true
      sizer: requests
      queue_size: 100
      num_consumers: 100
      block_on_overflow: true
      batch:
        enabled: false
    tls:
      insecure: true

processors:
  filter:
    error_mode: ignore
    logs:
      include:
        match_type: strict
        record_attributes:
          - key: ios.app.state
            value: active

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8086

  pipelines:
    logs/arrow:
      receivers: [otelarrow]
      processors: [filter]
      exporters: [otelarrow]
