receivers:
  # otelarrow/stdin is for regular traffic on the default gRPC port
  otelarrow/stdin:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
  # otelarrow/loopback receives OTel-Arrow traffic on port 4000
  otelarrow/loopback:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4000
      arrow:
        disabled: false

processors:
  batch:
  # the experiment processor routes 1 in 3 requests to the Arrow
  # loopback exporter
  experiment:
    table:
    - weight: 1
      exporters: [otelarrow/arrowout, logging/debug]
    - weight: 2
      exporters: [otelarrow/stdout, logging/info]

exporters:
  # otelarrow/stdout sends OTel Arrow to an external destination
  otelarrow/stdout:
    endpoint: ingest.lightstep.com:443
    headers:
      lightstep-access-token: "${LIGHTSTEP_ACCESS_TOKEN}"

  # otelarrow/arrowout sends standard OTal Arrow to an external destination
  otelarrow/arrowout:
    endpoint: 127.0.0.1:4000
    # wait_for_ready ensures the exporter doesn't fallback to standard
    # OTLP because the exporter has not started.
    wait_for_ready: true
    tls:
      insecure: true
    arrow:
      disabled: false
      num_streams: 1

  logging/info:      
    loglevel: info
  logging/debug:      
    loglevel: debug

service:
  pipelines:
    # the normal traces pipeline either routes directly to the
    # standard output or via the loopback.  it prints an info.
    traces/normal:
      receivers: [otelarrow/stdin]
      processors: [batch, experiment]
      exporters: [logging/info, otelarrow/stdout, otelarrow/arrowout]

    # experiment processes data send via Arrow through the loopback.
    # it prints a debug log.
    traces/experiment:
      receivers: [otelarrow/loopback]
      processors: [batch]
      exporters: [logging/debug, otelarrow/stdout]

  telemetry:
    metrics:
      address: localhost:8888
