receivers:
  otelarrow:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(attributes["exception.kind"], attributes["exception.type"])
          - delete_key(attributes, "exception.type")
          - set(attributes["exception.msg"], attributes["exception.message"])
          - delete_key(attributes, "exception.message")
          - set(attributes["exception.trace"], attributes["exception.stacktrace"])
          - delete_key(attributes, "exception.stacktrace")

exporters:
  otelarrow:
    endpoint: 'backend-service:1235'
    compression: none
    tls:
      insecure: true
    arrow:
      payload_compression: none
      disabled: false
    sending_queue:
      enabled: True
      wait_for_result: True
      block_on_overflow: True
      sizer: requests
      queue_size: 100

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8086
  pipelines:
    logs/arrow:
      receivers: [otelarrow]
      processors: [transform]
      exporters: [otelarrow]
    metrics/arrow:
      receivers: [otelarrow]
      exporters: [otelarrow]
    traces/arrow:
      receivers: [otelarrow]
      exporters: [otelarrow]