[package]
name = "otel-arrow-dfe-admin"
description = "OTAP dataflow engine admin endpoints"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
publish = true
keywords = ["telemetry", "opentelemetry", "otlp", "otap", "admin"]
categories = ["web-programming"]
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[features]
default = []
live-logs-ws = ["axum/ws"]
jemalloc-pprof = ["dep:jemalloc_pprof"]

[dependencies]
otel-arrow-dfe-admin-types = { workspace = true }
otel-arrow-dfe-config = { workspace = true }
otel-arrow-dfe-state = { workspace = true }
otel-arrow-dfe-telemetry = { workspace = true }
otel-arrow-dfe-engine = { workspace = true }

thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
tokio-util = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
include_dir = { workspace = true }
mime_guess = { workspace = true }

[target.'cfg(not(windows))'.dependencies]
pprof = { workspace = true }
jemalloc_pprof = { workspace = true, optional = true }

[dev-dependencies]
otel-arrow-dfe-telemetry-macros = { workspace = true }
