[package]
name = "otel-arrow-dfe-pdata-otlp-model"
description = "Build-time OTLP model generation for OTAP pdata"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
publish = true
keywords = ["telemetry", "opentelemetry", "otlp", "otap", "codegen"]
categories = ["development-tools::build-utils"]
rust-version.workspace = true

[lib]

[dependencies]
tonic-prost-build = { workspace = true }
