#!/bin/bash
# generate-dependency-changelog.sh
#
# Auto-generates a chloggen entry summarizing dependency-bot commits
# (renovate[bot], dependabot[bot]) since the last release tag for a
# given source tree. Renovate and Dependabot do not author chloggen
# entries themselves, so this script folds their PRs into one umbrella
# entry at release-prep time.
#
# Usage:
#   generate-dependency-changelog.sh <tree-path> <language-label> <output-yaml>
#
# Example:
#   generate-dependency-changelog.sh go Go go/.chloggen/auto-dependency-updates.yaml
#   generate-dependency-changelog.sh rust/otap-dataflow Rust \
#     rust/otap-dataflow/.chloggen/auto-dependency-updates.yaml
#
# Exits 0 with no file written when there are no qualifying commits.

set -euo pipefail

if [ $# -ne 3 ]; then
    echo "Usage: $0 <tree-path> <language-label> <output-yaml>" >&2
    exit 2
fi

TREE_PATH="$1"
LANGUAGE_LABEL="$2"
OUTPUT_YAML="$3"

# Find the most recent release tag (matches `vX.Y.Z`). If none exists,
# walk the entire history.
LAST_TAG=$(git tag --list 'v[0-9]*.[0-9]*.[0-9]*' --sort=-version:refname | head -n1 || true)

if [ -n "$LAST_TAG" ]; then
    RANGE="${LAST_TAG}..HEAD"
    echo "Scanning ${RANGE} for dependency-bot commits under ${TREE_PATH}/" >&2
else
    RANGE="HEAD"
    echo "No prior release tag found; scanning full history under ${TREE_PATH}/" >&2
fi

SUBJECTS_FILE=$(mktemp)
trap 'rm -f "$SUBJECTS_FILE"' EXIT

git log "$RANGE" \
    --author='renovate\[bot\]' \
    --author='dependabot\[bot\]' \
    --no-merges \
    --pretty=format:'%s' \
    -- "$TREE_PATH" \
    > "$SUBJECTS_FILE"

if [ ! -s "$SUBJECTS_FILE" ]; then
    echo "No dependency-bot commits found under ${TREE_PATH}/; skipping entry." >&2
    exit 0
fi

# Collect deduplicated PR numbers from `(#NNNN)` suffixes.
PR_NUMBERS=$(grep -oE '\(#[0-9]+\)$' "$SUBJECTS_FILE" \
    | grep -oE '[0-9]+' \
    | sort -un \
    || true)

if [ -z "$PR_NUMBERS" ]; then
    echo "No PR numbers found in dependency-bot subjects under ${TREE_PATH}/; skipping entry." >&2
    exit 0
fi

ISSUES_LIST=$(echo "$PR_NUMBERS" | paste -sd, - | sed 's/,/, /g')

mkdir -p "$(dirname "$OUTPUT_YAML")"
cat > "$OUTPUT_YAML" <<EOF
# Auto-generated by .github/workflows/scripts/generate-dependency-changelog.sh
# Aggregates renovate[bot] and dependabot[bot] PRs merged since ${LAST_TAG:-the beginning of history}.
change_type: enhancement
component: dependencies
note: Upgrade various ${LANGUAGE_LABEL} dependencies.
issues: [${ISSUES_LIST}]
subtext:
EOF

PR_COUNT=$(echo "$PR_NUMBERS" | wc -l | tr -d ' ')
echo "Wrote ${OUTPUT_YAML} aggregating ${PR_COUNT} ${LANGUAGE_LABEL} dependency PR(s)." >&2
