[package]
name = "parquet-query-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
arrow = { version = "55.2.0", features = ["prettyprint", "chrono-tz"] }
datafusion = "49.0.2"

tokio = {version = "1", features = ["full"] }


