receivers:
  test:
processors:
  noop:
exporters:
  test:
extensions: {}
service:
  extensions: []
  pipelines:
    test:
      receivers:
        - test
      processors:
        - noop
      exporters:
        - test
