#!/bin/sh

set -eu

if ! cargo +nightly fmt --all -- --check
then
    echo "There are some code style issues."
    exit 1
fi

if ! cargo clippy --all-targets -- -D warnings
then
    echo "There are some clippy issues."
    exit 1
fi

if ! cargo test --all
then
    echo "There are some test issues."
    exit 1
fi

if ! cargo deny check
then
    echo "There are some cargo deny issues."
    exit 1
fi

exit 0