settings:
  default_pipeline_ctrl_msg_channel_size: 100
  default_node_ctrl_msg_channel_size: 100
  default_pdata_channel_size: 100

nodes:
  receiver:
    kind: receiver
    plugin_urn: "urn:otel:syslog_cef:receiver"
    out_ports:
      out_port:
        destinations:
          - attr
        dispatch_strategy: round_robin
    config:
      listening_addr: "0.0.0.0:4317"
      protocol: udp
  attr:
    kind: processor
    plugin_urn: "urn:otap:processor:attributes_processor"
    out_ports:
      out_port:
        destinations:
          - exporter
        dispatch_strategy: round_robin
    config:
      actions:
        - action: "rename"
          source_key: "name"
          destination_key: "name2"
          apply_to: ["scope"]
  exporter:
    kind: exporter
    plugin_urn: "urn:otel:otlp:exporter"
    config:
      grpc_endpoint: "http://{{backend_hostname}}:1235"
      compression_method: gzip
