[package]
name = "otap-df-perf"
description = "Perf exporter"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
otap-df-engine = { path = "../engine" }
otap-df-otap = { path = "../otap" }
sysinfo = "0.35.1"
byte-unit = "4"
fluke-hpack = "0.3.1"
serde = {version="1", features=["derive"]}
thiserror = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
portpicker = "0.1.1"