[package]
name = "otap-df-expohisto"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
rust-version.workspace = true
description = "Allocation-free OpenTelemetry exponential histogram"

[features]
default = ["std"]

# Enables `std::error::Error` impls.
std = []

[dependencies]

[lints]
workspace = true
