msrv = "1.86.0"
warn-on-all-wildcard-imports = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true

# Disallow specific methods
disallowed-methods = []

# Disallow specific types
disallowed-types = [
    { path = "once_cell::sync::Lazy", reason = "Please use `std::sync::LazyLock` instead." },
]

# Disallow specific macros
disallowed-macros = [
    { path = "lazy_static::lazy_static", reason = "Please use `std::sync::LazyLock` instead." },
]

doc-valid-idents = [
    "OTEL",
    "..",   # add the default list
]
