// This file is @generated by prost-build.
#[crate::pdata::otlp::qualified("opentelemetry.proto.resource.v1.Resource")]
#[derive(crate::pdata::otlp::Message)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Resource {
    #[prost(message, repeated, tag="1")]
    pub attributes: ::prost::alloc::vec::Vec<super::super::common::v1::KeyValue>,
    #[prost(uint32, tag="2")]
    pub dropped_attributes_count: u32,
    #[prost(message, repeated, tag="3")]
    pub entity_refs: ::prost::alloc::vec::Vec<super::super::common::v1::EntityRef>,
}
