// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/open-telemetry/otel-arrow/pkg/otel/arrow_record (interfaces: ProducerAPI,ConsumerAPI)
//
// Generated by this command:
//
//	mockgen -package mock . ProducerAPI,ConsumerAPI
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	v1 "github.com/open-telemetry/otel-arrow/api/experimental/arrow/v1"
	plog "go.opentelemetry.io/collector/pdata/plog"
	pmetric "go.opentelemetry.io/collector/pdata/pmetric"
	ptrace "go.opentelemetry.io/collector/pdata/ptrace"
	gomock "go.uber.org/mock/gomock"
)

// MockProducerAPI is a mock of ProducerAPI interface.
type MockProducerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockProducerAPIMockRecorder
}

// MockProducerAPIMockRecorder is the mock recorder for MockProducerAPI.
type MockProducerAPIMockRecorder struct {
	mock *MockProducerAPI
}

// NewMockProducerAPI creates a new mock instance.
func NewMockProducerAPI(ctrl *gomock.Controller) *MockProducerAPI {
	mock := &MockProducerAPI{ctrl: ctrl}
	mock.recorder = &MockProducerAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProducerAPI) EXPECT() *MockProducerAPIMockRecorder {
	return m.recorder
}

// BatchArrowRecordsFromLogs mocks base method.
func (m *MockProducerAPI) BatchArrowRecordsFromLogs(arg0 plog.Logs) (*v1.BatchArrowRecords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchArrowRecordsFromLogs", arg0)
	ret0, _ := ret[0].(*v1.BatchArrowRecords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchArrowRecordsFromLogs indicates an expected call of BatchArrowRecordsFromLogs.
func (mr *MockProducerAPIMockRecorder) BatchArrowRecordsFromLogs(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchArrowRecordsFromLogs", reflect.TypeOf((*MockProducerAPI)(nil).BatchArrowRecordsFromLogs), arg0)
}

// BatchArrowRecordsFromMetrics mocks base method.
func (m *MockProducerAPI) BatchArrowRecordsFromMetrics(arg0 pmetric.Metrics) (*v1.BatchArrowRecords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchArrowRecordsFromMetrics", arg0)
	ret0, _ := ret[0].(*v1.BatchArrowRecords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchArrowRecordsFromMetrics indicates an expected call of BatchArrowRecordsFromMetrics.
func (mr *MockProducerAPIMockRecorder) BatchArrowRecordsFromMetrics(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchArrowRecordsFromMetrics", reflect.TypeOf((*MockProducerAPI)(nil).BatchArrowRecordsFromMetrics), arg0)
}

// BatchArrowRecordsFromTraces mocks base method.
func (m *MockProducerAPI) BatchArrowRecordsFromTraces(arg0 ptrace.Traces) (*v1.BatchArrowRecords, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchArrowRecordsFromTraces", arg0)
	ret0, _ := ret[0].(*v1.BatchArrowRecords)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchArrowRecordsFromTraces indicates an expected call of BatchArrowRecordsFromTraces.
func (mr *MockProducerAPIMockRecorder) BatchArrowRecordsFromTraces(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchArrowRecordsFromTraces", reflect.TypeOf((*MockProducerAPI)(nil).BatchArrowRecordsFromTraces), arg0)
}

// Close mocks base method.
func (m *MockProducerAPI) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockProducerAPIMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockProducerAPI)(nil).Close))
}

// MockConsumerAPI is a mock of ConsumerAPI interface.
type MockConsumerAPI struct {
	ctrl     *gomock.Controller
	recorder *MockConsumerAPIMockRecorder
}

// MockConsumerAPIMockRecorder is the mock recorder for MockConsumerAPI.
type MockConsumerAPIMockRecorder struct {
	mock *MockConsumerAPI
}

// NewMockConsumerAPI creates a new mock instance.
func NewMockConsumerAPI(ctrl *gomock.Controller) *MockConsumerAPI {
	mock := &MockConsumerAPI{ctrl: ctrl}
	mock.recorder = &MockConsumerAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsumerAPI) EXPECT() *MockConsumerAPIMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockConsumerAPI) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockConsumerAPIMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockConsumerAPI)(nil).Close))
}

// LogsFrom mocks base method.
func (m *MockConsumerAPI) LogsFrom(arg0 *v1.BatchArrowRecords) ([]plog.Logs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogsFrom", arg0)
	ret0, _ := ret[0].([]plog.Logs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LogsFrom indicates an expected call of LogsFrom.
func (mr *MockConsumerAPIMockRecorder) LogsFrom(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogsFrom", reflect.TypeOf((*MockConsumerAPI)(nil).LogsFrom), arg0)
}

// MetricsFrom mocks base method.
func (m *MockConsumerAPI) MetricsFrom(arg0 *v1.BatchArrowRecords) ([]pmetric.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MetricsFrom", arg0)
	ret0, _ := ret[0].([]pmetric.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MetricsFrom indicates an expected call of MetricsFrom.
func (mr *MockConsumerAPIMockRecorder) MetricsFrom(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MetricsFrom", reflect.TypeOf((*MockConsumerAPI)(nil).MetricsFrom), arg0)
}

// TracesFrom mocks base method.
func (m *MockConsumerAPI) TracesFrom(arg0 *v1.BatchArrowRecords) ([]ptrace.Traces, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TracesFrom", arg0)
	ret0, _ := ret[0].([]ptrace.Traces)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TracesFrom indicates an expected call of TracesFrom.
func (mr *MockConsumerAPIMockRecorder) TracesFrom(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TracesFrom", reflect.TypeOf((*MockConsumerAPI)(nil).TracesFrom), arg0)
}
