// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/open-telemetry/otel-arrow/collector/cmd/otelarrowcol

go 1.20

require (
	github.com/open-telemetry/otel-arrow/collector v0.0.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/headerssetterextension v0.83.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.83.0
	github.com/open-telemetry/otel-arrow/collector v0.0.0
	github.com/open-telemetry/otel-arrow/collector v0.0.0
	github.com/lightstep/telemetry-generator/generatorreceiver v0.12.0
	go.opentelemetry.io/collector/exporter/loggingexporter v0.83.0
	go.opentelemetry.io/collector/exporter/otlphttpexporter v0.83.0
	github.com/open-telemetry/otel-arrow/collector v0.0.0
	github.com/open-telemetry/otel-arrow/collector v0.0.0
	go.opentelemetry.io/collector/processor/batchprocessor v0.83.0
	go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.83.0
	github.com/open-telemetry/otel-arrow/collector v0.0.0
	github.com/open-telemetry/otel-arrow/collector v0.0.0
	go.opentelemetry.io/collector v0.83.0
)














replace github.com/open-telemetry/otel-arrow v0.0.0 => ../../..
replace github.com/open-telemetry/otel-arrow/collector v0.0.0 => ../../

// ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules
replace cloud.google.com/go => cloud.google.com/go v0.110.2
