// Code generated by "go.opentelemetry.io/collector/cmd/builder". DO NOT EDIT.

module github.com/open-telemetry/otel-arrow/collector/cmd/otelarrowcol

go 1.20

require (
	github.com/open-telemetry/otel-arrow/collector v0.6.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/headerssetterextension v0.88.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.88.0
	github.com/open-telemetry/opentelemetry-collector-contrib/extension/pprofextension v0.88.0
	github.com/open-telemetry/otel-arrow/collector v0.6.0
	github.com/open-telemetry/otel-arrow/collector v0.6.0
	github.com/lightstep/telemetry-generator/generatorreceiver v0.15.0
	github.com/open-telemetry/otel-arrow/collector v0.6.0
	go.opentelemetry.io/collector/exporter/debugexporter v0.88.0
	go.opentelemetry.io/collector/exporter/otlphttpexporter v0.88.0
	github.com/open-telemetry/otel-arrow/collector v0.6.0
	github.com/open-telemetry/otel-arrow/collector v0.6.0
	github.com/open-telemetry/otel-arrow/collector v0.6.0
	github.com/open-telemetry/otel-arrow/collector v0.6.0
	go.opentelemetry.io/collector/otelcol v0.88.0
)

require (
	github.com/knadh/koanf/maps v0.1.1 // indirect
	github.com/knadh/koanf/providers/confmap v0.1.0 // indirect
)















// ambiguous import: found package cloud.google.com/go/compute/metadata in multiple modules
replace cloud.google.com/go => cloud.google.com/go v0.110.9
