[package]
name = "otap-df-signal-type-router"
description = "Signal type router processor for OTAP dataflow engine"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
otap-df-engine = { path = "../engine" }
otap-df-config = { path = "../config" }
otap-df-otap = { path = "../otap" }

thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
async-trait = { workspace = true }
otel-arrow-rust = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
env_logger = "0.11.5"
