package constants

const TIME_UNIX_NANO string = "time_unix_nano"
const OBSERVED_TIME_UNIX_NANO string = "observed_time_unix_nano"
const SEVERITY_NUMBER string = "severity_number"
const SEVERITY_TEXT string = "severity_text"
const DROPPED_ATTRIBUTES_COUNT string = "dropped_attributes_count"
const FLAGS string = "flags"
const TRACE_ID string = "trace_id"
const SPAN_ID string = "span_id"
const ATTRIBUTES string = "attributes"
const RESOURCE string = "resource"
const SCOPE_LOGS string = "scope_logs"
const NAME string = "name"
const VERSION string = "version"
const BODY string = "body"
