package constants

const TIME_UNIX_NANO string = "time_unix_nano"
const START_TIME_UNIX_NANO string = "start_time_unix_nano"
const END_TIME_UNIX_NANO string = "end_time_unix_nano"
const OBSERVED_TIME_UNIX_NANO string = "observed_time_unix_nano"
const SEVERITY_NUMBER string = "severity_number"
const SEVERITY_TEXT string = "severity_text"
const DROPPED_ATTRIBUTES_COUNT string = "dropped_attributes_count"
const FLAGS string = "flags"
const TRACE_ID string = "trace_id"
const TRACE_STATE string = "trace_state"
const SPAN_ID string = "span_id"
const PARENT_SPAN_ID string = "parent_span_id"
const ATTRIBUTES string = "attributes"
const RESOURCE string = "resource"
const SCOPE_LOGS string = "scope_logs"
const SCOPE_SPANS string = "scope_spans"
const NAME string = "name"
const KIND string = "kind"
const VERSION string = "version"
const BODY string = "body"
const STATUS string = "status"
const STATUS_MESSAGE string = "status_message"
