name: Crosscutting-CI

permissions:
  contents: read

on:
  pull_request:
    branches: [ main ]

  sanity:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: run sanitycheck.py
      run: python3 ./tools/sanitycheck.py
