# This workflow is for various linting tasks that act in bulk over the repository.
# Scoped linting (i.e. code formatting) should be done in the respective language-specific workflows.
name: Repo Lint

permissions: read-all

on:
  pull_request:
    branches:
      - main
  merge_group:

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
      with:
        egress-policy: audit

    - name: check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: run markdownlint
      uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
      with:
        globs: |
          **/*.md

  link-check:
    runs-on: ubuntu-latest

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: check out code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: run lychee
      uses: lycheeverse/lychee-action@e7477775783ea5526144ba13e8db5eec57747ce8 # v2.9.0
      with:
        args: --verbose --no-progress --config .github/lychee.toml './**/*.md'
        fail: true

  sanity:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: run sanitycheck.py
      run: python3 ./tools/sanitycheck.py

    - name: run sanitycheck.py unit tests
      run: python3 ./tools/test_sanitycheck.py

  renovate-config-validation:
    runs-on: ubuntu-latest

    steps:
    - name: check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up Node.js
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: '24'

    - name: Validate Renovate config
      run: npx --yes --package renovate -- renovate-config-validator --strict
