# This workflow is for running CI on experimental Rust code in the repository.
# It is much slimmer than the Rust-CI workflow and doesn't require the same level of maturity.
name: Rust-Experimental
permissions:
  contents: read

on:
  # run this job on every push and pull request
  # only for changes in the rust directory
  push:
    paths:
      - 'rust/**'
      - .github/workflows/rust-experimental.yml
      # otap-dataflow is covered by the main Rust-CI workflow
      - '!rust/otap-dataflow/**'
  pull_request:
    paths:
      - 'rust/**'
      - .github/workflows/rust-experimental.yml
      # otap-dataflow is covered by the main Rust-CI workflow
      - '!rust/otap-dataflow/**'
      

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        folder: [beaubourg, otel-arrow-rust, experimental/query_abstraction, experimental/syslog-cef-receivers]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - uses: arduino/setup-protoc@c65c819552d16ad3c9b72d9dfd5ba5237b9c906b # v3.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dtolnay/rust-toolchain@56f84321dbccf38fb67ce29ab63e4754056677e0 # latest on /master branch as of 2025-04-02
        with:
          toolchain: stable
      - name: cargo test ${{ matrix.folder }}
        run: cargo test
        working-directory: ./rust/${{ matrix.folder }}