name: Rust-Audit
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - 'rust/otap-dataflow/Cargo.toml'
  schedule:
    - cron: '0 2 * * 1' # run at 2 AM UTC every Monday

jobs:
  audit:
    strategy:
      fail-fast: false
      matrix:
        folder: [otap-dataflow]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9
        with:
          toolchain: stable
      - name: cargo install cargo-audit
        run: cargo install cargo-audit
      - name: cargo audit ${{ matrix.folder }}
        run: cargo audit
        working-directory: ./rust/${{ matrix.folder }}
