name: "Tidy Renovate PRs"
permissions:
  contents: read

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  tidy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'renovate[bot]' && github.event.pull_request.head.repo.fork == false }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: "1.26.0"
      - name: make genotelarrowcol
        # This also runs 'go mod tidy' as part of its process
        run: make genotelarrowcol
      - name: Commit changes
        run: |
          # Configure git for otelbot
          git config user.name otelbot
          git config user.email 197425009+otelbot@users.noreply.github.com

          if ! git diff --exit-code; then
            git add .
            git commit -m "make genotelarrowcol"
            git push
          fi
