// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

//! Core value types shared across the topic crate.

use otap_df_config::SubscriptionGroupName;
use otap_df_config::topic::TopicBroadcastOnLagPolicy;
use otap_df_telemetry::otel_warn;
use parking_lot::Mutex;
use std::collections::HashMap;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;
use tokio::sync::{Notify, OwnedSemaphorePermit};
use tokio::time::{Instant, sleep_until};

/// A delivered message envelope carrying a broker-assigned id and the payload.
#[derive(Debug)]
pub struct Envelope<T> {
    /// Broker-assigned message identifier.
    pub id: u64,
    /// Whether the message was published through the tracked-outcome path.
    pub tracked: bool,
    /// Shared payload reference delivered to subscribers.
    pub payload: Arc<T>,
}

impl<T> Clone for Envelope<T> {
    fn clone(&self) -> Self {
        Self {
            id: self.id,
            tracked: self.tracked,
            payload: Arc::clone(&self.payload),
        }
    }
}

/// Items yielded by `Subscription::recv`.
#[derive(Debug)]
pub enum RecvItem<T> {
    /// A normal message.
    Message(Envelope<T>),
    /// Notification that this broadcast subscriber lagged and missed messages.
    Lagged {
        /// Number of dropped messages for this subscriber.
        missed: u64,
    },
}

/// Result of a non-blocking publish attempt.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PublishOutcome {
    /// Message was accepted for delivery.
    Published,
    /// Message was dropped because at least one balanced queue was full.
    ///
    /// For mixed topics, broadcast delivery may still succeed even when this
    /// outcome is returned.
    DroppedOnFull,
}

/// Terminal outcome for a tracked publish.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum TrackedPublishOutcome {
    /// Message processing succeeded.
    Ack,
    /// Message processing failed downstream.
    Nack {
        /// Reason attached by the downstream nack or generated by the runtime.
        reason: Arc<str>,
    },
    /// Message did not receive a terminal Ack/Nack before the configured timeout.
    TimedOut,
    /// The topic closed before the tracked message received a terminal outcome.
    TopicClosed,
}

/// Result of a non-blocking tracked publish attempt.
#[derive(Debug)]
pub enum TrackedTryPublishOutcome {
    /// Message was accepted for tracked delivery.
    Published(TrackedPublishReceipt),
    /// Message was dropped because a balanced queue was full.
    DroppedOnFull,
    /// No tracked-outcome slot was available for this publisher.
    MaxInFlightReached,
}

/// Opaque capacity token for one tracked publish.
///
/// The topic handle acquires this token before calling tracked publish APIs.
/// Backend implementations only need to hold it until the tracked publish
/// reaches a terminal outcome, at which point dropping the token releases the
/// in-flight capacity back to the publisher.
pub struct TrackedPublishPermit(Option<OwnedSemaphorePermit>);

impl std::fmt::Debug for TrackedPublishPermit {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("TrackedPublishPermit(..)")
    }
}

impl TrackedPublishPermit {
    pub(crate) fn from_tokio_owned(permit: OwnedSemaphorePermit) -> Self {
        Self(Some(permit))
    }
}

impl Drop for TrackedPublishPermit {
    fn drop(&mut self) {
        _ = self.0.take();
    }
}

/// Shared tracker for tracked publish receipts and timeout handling.
///
/// Backends can register tracked publishes in this tracker, then resolve or
/// discard them later by message id. The tracker runs one shared timeout worker
/// for all pending tracked publishes.
#[derive(Clone)]
pub struct TrackedPublishTracker {
    inner: Arc<TrackedPublishTrackerInner>,
}

struct TrackedPublishTrackerInner {
    entries: Mutex<HashMap<u64, Arc<TrackedPublishEntry>>>,
    closed: AtomicBool,
    wakeups: Notify,
    timeout_worker_started: AtomicBool,
}

impl std::fmt::Debug for TrackedPublishTracker {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let pending = self.inner.entries.lock().len();
        f.debug_struct("TrackedPublishTracker")
            .field("pending", &pending)
            .finish()
    }
}

impl Default for TrackedPublishTracker {
    fn default() -> Self {
        Self::new()
    }
}

impl TrackedPublishTracker {
    /// Create a new empty tracked publish tracker.
    #[must_use]
    pub fn new() -> Self {
        Self {
            inner: Arc::new(TrackedPublishTrackerInner {
                entries: Mutex::new(HashMap::new()),
                closed: AtomicBool::new(false),
                wakeups: Notify::new(),
                timeout_worker_started: AtomicBool::new(false),
            }),
        }
    }

    /// Register one tracked publish and return its receipt.
    ///
    /// `timeout` starts once this method admits the tracked publish into the
    /// tracker. If no terminal outcome is resolved before that deadline, the
    /// receipt resolves as [`TrackedPublishOutcome::TimedOut`].
    ///
    /// If the tracker was already closed, the returned receipt resolves
    /// immediately as [`TrackedPublishOutcome::TopicClosed`].
    pub fn register(
        &self,
        message_id: u64,
        timeout: Duration,
        permit: TrackedPublishPermit,
    ) -> TrackedPublishReceipt {
        if self.inner.closed.load(Ordering::Acquire) {
            let entry = Arc::new(TrackedPublishEntry::new(Instant::now(), permit));
            let _resolved = entry.resolve(TrackedPublishOutcome::TopicClosed);
            return TrackedPublishReceipt::new(message_id, entry);
        }

        self.ensure_timeout_worker();
        let entry = Arc::new(TrackedPublishEntry::new(Instant::now() + timeout, permit));
        let replaced = self
            .inner
            .entries
            .lock()
            .insert(message_id, Arc::clone(&entry));
        if replaced.is_some() {
            otel_warn!(
                "topic.tracked_publish.duplicate_message_id",
                message_id = message_id,
                message = "Tracked publish tracker registered a duplicate message id and overwrote the previous entry"
            );
        }
        self.inner.wakeups.notify_one();
        TrackedPublishReceipt::new(message_id, entry)
    }

    /// Resolve one tracked publish by message id.
    ///
    /// Returns `true` if this call resolved a pending publish. Returns `false`
    /// if the message id was not tracked or had already been resolved.
    #[must_use]
    pub fn resolve(&self, message_id: u64, outcome: TrackedPublishOutcome) -> bool {
        let Some(entry) = self.inner.entries.lock().remove(&message_id) else {
            return false;
        };
        let resolved = entry.resolve(outcome);
        self.inner.wakeups.notify_one();
        resolved
    }

    /// Discard one tracked publish without producing an outcome.
    ///
    /// This releases the in-flight slot associated with the publish.
    #[must_use]
    pub fn discard(&self, message_id: u64) -> bool {
        let removed = self.inner.entries.lock().remove(&message_id).is_some();
        if removed {
            self.inner.wakeups.notify_one();
        }
        removed
    }

    /// Resolve all pending tracked publishes as
    /// [`TrackedPublishOutcome::TopicClosed`].
    pub fn close_all(&self) {
        self.inner.closed.store(true, Ordering::Release);
        let drained = {
            let mut entries = self.inner.entries.lock();
            entries.drain().map(|(_, entry)| entry).collect::<Vec<_>>()
        };
        for entry in drained {
            let _resolved = entry.resolve(TrackedPublishOutcome::TopicClosed);
        }
        self.inner.wakeups.notify_waiters();
    }

    fn ensure_timeout_worker(&self) {
        if self
            .inner
            .timeout_worker_started
            .compare_exchange(false, true, Ordering::AcqRel, Ordering::Acquire)
            .is_ok()
        {
            let tracker = self.clone();
            _ = tokio::spawn(async move {
                tracker.timeout_worker().await;
            });
        }
    }

    async fn timeout_worker(self) {
        loop {
            if self.inner.closed.load(Ordering::Acquire) && self.inner.entries.lock().is_empty() {
                break;
            }

            let next_deadline = self.next_deadline();
            match next_deadline {
                Some(deadline) => {
                    tokio::select! {
                        _ = sleep_until(deadline) => self.resolve_expired(deadline),
                        _ = self.inner.wakeups.notified() => {}
                    }
                }
                None => {
                    self.inner.wakeups.notified().await;
                }
            }
        }
    }

    fn next_deadline(&self) -> Option<Instant> {
        self.inner
            .entries
            .lock()
            .values()
            .filter(|entry| entry.is_pending())
            .map(|entry| entry.deadline())
            .min()
    }

    fn resolve_expired(&self, now: Instant) {
        let expired = {
            let mut entries = self.inner.entries.lock();
            let expired_ids = entries
                .iter()
                .filter_map(|(id, entry)| {
                    (entry.is_pending() && entry.deadline() <= now).then_some(*id)
                })
                .collect::<Vec<_>>();
            expired_ids
                .into_iter()
                .filter_map(|id| entries.remove(&id))
                .collect::<Vec<_>>()
        };

        for entry in expired {
            let _resolved = entry.resolve(TrackedPublishOutcome::TimedOut);
        }
    }
}

/// Default configuration used when creating a tracked publisher from a topic handle.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TopicPublishOutcomeConfig {
    /// Maximum number of unresolved tracked publishes per tracked publisher.
    ///
    /// This limit is enforced before entering the topic runtime by requiring a
    /// caller-owned permit for each tracked publish.
    pub max_in_flight: usize,
    /// Maximum time to wait before a tracked publish resolves as timed out.
    ///
    /// The timer starts once the topic accepts the tracked publish.
    pub timeout: Duration,
}

impl Default for TopicPublishOutcomeConfig {
    fn default() -> Self {
        Self {
            max_in_flight: 1024,
            timeout: Duration::from_secs(30),
        }
    }
}

/// Receipt returned by tracked publish calls.
///
/// The receipt can be awaited for its terminal outcome via
/// [`TrackedPublishReceipt::wait_for_outcome`]. Dropping the receipt does not
/// cancel the underlying tracked publish or release its in-flight slot early;
/// the slot is released only when the publish reaches a terminal outcome or
/// times out.
pub struct TrackedPublishReceipt {
    message_id: u64,
    entry: Arc<TrackedPublishEntry>,
}

impl std::fmt::Debug for TrackedPublishReceipt {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TrackedPublishReceipt")
            .field("message_id", &self.message_id)
            .finish()
    }
}

impl TrackedPublishReceipt {
    pub(crate) fn new(message_id: u64, entry: Arc<TrackedPublishEntry>) -> Self {
        Self { message_id, entry }
    }

    /// Broker-assigned message identifier.
    #[must_use]
    pub const fn message_id(&self) -> u64 {
        self.message_id
    }

    /// Wait for the terminal tracked outcome.
    ///
    /// Consuming the receipt only waits for the already-tracked outcome. It
    /// does not own the tracked publish lifecycle, so dropping the receipt
    /// before awaiting does not cancel tracking.
    pub async fn wait_for_outcome(self) -> TrackedPublishOutcome {
        self.entry.wait_for_outcome().await
    }
}

#[derive(Debug, Clone)]
enum TrackedPublishState {
    Pending,
    Resolved(TrackedPublishOutcome),
}

/// Internal shared state for one tracked publish receipt.
pub(crate) struct TrackedPublishEntry {
    state: Mutex<TrackedPublishState>,
    deadline: Instant,
    permit: Mutex<Option<TrackedPublishPermit>>,
    notify: Notify,
}

impl TrackedPublishEntry {
    pub(crate) fn new(deadline: Instant, permit: TrackedPublishPermit) -> Self {
        Self {
            state: Mutex::new(TrackedPublishState::Pending),
            deadline,
            permit: Mutex::new(Some(permit)),
            notify: Notify::new(),
        }
    }

    #[must_use]
    pub(crate) fn deadline(&self) -> Instant {
        self.deadline
    }

    #[must_use]
    pub(crate) fn is_pending(&self) -> bool {
        matches!(*self.state.lock(), TrackedPublishState::Pending)
    }

    pub(crate) fn resolve(&self, outcome: TrackedPublishOutcome) -> bool {
        let mut state = self.state.lock();
        if matches!(*state, TrackedPublishState::Resolved(_)) {
            return false;
        }
        *state = TrackedPublishState::Resolved(outcome);
        drop(state);
        _ = self.permit.lock().take();
        self.notify.notify_waiters();
        true
    }

    async fn wait_for_outcome(&self) -> TrackedPublishOutcome {
        loop {
            let notified = self.notify.notified();
            if let Some(outcome) = self.current_outcome() {
                return outcome;
            }
            notified.await;
        }
    }

    fn current_outcome(&self) -> Option<TrackedPublishOutcome> {
        match &*self.state.lock() {
            TrackedPublishState::Pending => None,
            TrackedPublishState::Resolved(outcome) => Some(outcome.clone()),
        }
    }
}

/// Subscription mode chosen by the subscriber.
#[derive(Debug, Clone)]
pub enum SubscriptionMode {
    /// Balanced (consumer-group) mode: each message goes to exactly one subscriber in the group.
    Balanced {
        /// Consumer-group identifier.
        group: SubscriptionGroupName,
    },
    /// Broadcast mode: each subscriber gets every message with configurable lag behavior.
    Broadcast,
}

/// Options provided at subscription time.
#[derive(Debug, Clone, Default)]
pub struct SubscriberOptions {}

/// Options for creating/opening a topic.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TopicOptions {
    /// Only balanced (consumer-group) subscriptions.
    BalancedOnly {
        /// Capacity for balanced consumer-group channels.
        capacity: usize,
    },
    /// Only broadcast subscriptions.
    BroadcastOnly {
        /// Ring-buffer capacity for broadcast subscribers.
        capacity: usize,
        /// Behavior when a broadcast subscriber falls behind the retained ring window.
        on_lag: TopicBroadcastOnLagPolicy,
    },
    /// Both balanced and broadcast subscriptions.
    Mixed {
        /// Capacity for balanced consumer-group channels.
        balanced_capacity: usize,
        /// Ring-buffer capacity for broadcast subscribers.
        broadcast_capacity: usize,
        /// Behavior when a broadcast subscriber falls behind the retained ring window.
        on_lag: TopicBroadcastOnLagPolicy,
    },
}

impl TopicOptions {
    /// Default balanced channel capacity.
    pub const DEFAULT_BALANCED_CAPACITY: usize = 1024;
    /// Default broadcast ring-buffer capacity.
    pub const DEFAULT_BROADCAST_CAPACITY: usize = 1024;
}

impl Default for TopicOptions {
    fn default() -> Self {
        Self::Mixed {
            balanced_capacity: TopicOptions::DEFAULT_BALANCED_CAPACITY,
            broadcast_capacity: TopicOptions::DEFAULT_BROADCAST_CAPACITY,
            on_lag: TopicBroadcastOnLagPolicy::DropOldest,
        }
    }
}
